version: '3'

services:

    prod:
        build: .
        command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
        volumes:
            - "./repo/prod:/var/spool/apt-mirror"

    server:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        restart: always
        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - "./repo:/mirror:ro"
        ports:
            - "8080:80"

    hom:
        build: .
        command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
        volumes:
            - "./repo/hom:/var/spool/apt-mirror"
    des:
        build: .
        command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
        volumes:
            - "./repo/des:/var/spool/apt-mirror"
    lab:
        build: .
        command: bash -c "apt-mirror && bash /apt-mirror/postmirror.sh"
        volumes:
            - "./repo/lab:/var/spool/apt-mirror"
